version: "3"

services: 
    frontend:
        links: 
            - backend
        build: 
            context: ./frontend
            dockerfile: Dockerfile.dev
        tty: true
        env_file: 
            - ./frontend/.env
        volumes: 
            - /app/node_modules
            - ./frontend:/app
    nginx: 
        ports: 
            - 3050:80
        restart: always
        build:
            context: ./nginx
        depends_on: 
            - backend
    mongodb:
        image: mongo
        restart: always
        env_file: 
            - docker-compose-mongodb.env
        volumes: 
            - ./datadb:/data/db
    
    # mongodb_ui: 
    #     image: mongo-express
    #     restart: always
    #     links:
    #         - mongodb
    #     ports:
    #         - 8081:8081
    #     env_file: 
    #         - docker-compose-mongodb_ui.env
    
    backend:
        depends_on: 
            - mongodb
        links: 
            - mongodb
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        restart: always
        env_file: 
            - docker-compose-backend.env
        volumes: 
            - /app/node_modules
            - ./backend/:/app